name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
    
    - name: Install dependencies
      run: |
        cd src/tests
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: playwright install --with-deps chromium
    
    - name: Run tests
      run: |
        cd src/tests
        pytest -v
